-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHGLOBAL
-----------------------------------------------------------------------------------------------------------------------------------------
local vehglobal = {
	["*"] = { "Desconhecido", "Comum", 0 },

	["volatus"] = { "Volatus", "Premium", 0 },
	["supervolito"] = { "Supervolito", "Premium", 0 },
	["annihilator2"] = { "Annihilator 2", "Premium", 0 },
	["rmodmartin"] = { "Aston Martin", "Premium", 0 },
	["rmodaudiai"] = { "Audi AI-RACE", "Premium", 0 },
	["rmodrs5"] = {	"Audi RS5 Coupe", "Premium", 0 },
	["rmodrs7"] = {	"Audi RS7", "Premium", 0 },
	["rmodbacalar"] = {	"Bentley Bacalar", "Premium", 0 },
	["rmodbentayga"] = { "Bentley Bentayga", "Premium", 0 },
	["rmodi8ks"] = { "BMW I8 KS", "Premium", 0 },
	["rmodmi8lb"] = { "BMW I8 LB", "Premium", 0 },
	["rmodm4"] = { "BMW M4", "Premium", 0 },
	["rmodm5e34"] = { "BMW M5 E34", "Premium", 0 },
	["rmodx6"] = { "BMW X6M", "Premium", 0 },
	["rmodctsv"] = { "Cadillac CTS", "Premium", 0 },
	["rmodcamaro"] = { "Chevrolet Camaro", "Premium", 0 },
	["rmodcharger"] = { "Dodge Charger Hellcat", "Premium", 0 },
	["rmodf8"] = { "Ferrari F8T", "Premium", 0 },
	["rmodf40"] = { "Ferrari F40", "Premium", 0 },
	["rmodjeep"] = { "Jeep Grand Cherokee", "Premium", 0 },
	["rmodjesko"] = { "Koenigsegg Jesko", "Premium", 0 },
	["rmodessenza"] = { "Lamborghini Essenza", "Premium", 0 },
	["rmodsianr"] = { "Lamborghini Sian R", "Premium", 0 },
	["rmodp1gtr"] = { "McLaren P1 GTR", "Premium", 0 },
	["rmodamggt"] = { "Mercedes-AMGGT Black", "Premium", 0 },
	["rmodg65"] = { "Mercedes-Benz AMG G65", "Premium", 0 },
	["rmodg63"] = {	"Mercedes-Benz G63 Edition", "Premium", 0 },
	["rmodmonstergt"] = { "Mercedes-Benz GT 63SM", "Premium", 0 },
	["rmodgt63"] = { "Mercedes-Benz GT63S", "Premium", 0 },
	["rmodmonsterr34"] = { "Nissan Skyline R34M", "Premium", 0 },
	["rmodskyline34"] = { "Nissan Skyline R34", "Premium", 0 },
	["rmodporsche918"] = { "Porsche 918 Spyder", "Premium", 0 },
	["rmodmonster"] = {	"Regalia Monster", "Premium", 0 },
	["rmodsuprapandem"] = { "Toyota Supra Pandem", "Premium", 0 },
}